# Documentation: https://roots.io/trellis/docs/troubleshooting/#composer-install-host-key-verification-failed

# Host keys to add to known_hosts, e.g.,
#   - git host for Bedrock-based project (`repo` variable in `wordpress_sites`)
#   - git hosts in Bedrock project's composer.json
known_hosts:
  - name: github.com
    key: github.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDdaoByymHhiwrE/aDImvrOyPYPZHkKg2FuxSqKJBd9IKOPx7t27M3NtZ4IWheqcJ6S641XRjd83M34LHNE6BNdjSgHSrB3MAMhFNtOA2bdge5m23xZ19+YC7oWpFljqVus05dbQltJGFk+Ev70dE+1UIyfHfazWPRoGmB1kRxdL1RxndZdYTVLg2a27/K3E6mUaxIMi1akQxSobbaRvnYHkwPAXWVm9obLTgUcY7SmjiC4iHX27wr7Gs89KsT65rAv8wKH5eej6uBfTXmoZ6hj7L0vepznEdCjRZMyuBJfcsLT9UNnilnrphXLs2LxLaeeN/jI1hu4xZLtMkIhW5sUGE9E8IuCctEAOxcEAngWpoSvq5D2lgBsGPZC87VzsetK0z0kpkyzUb/Y+ryMSDcyZ4ap90qAD7NP8Hm5YMhf/P0l8b+Nbh435k56twwNbaTWg0LapnW/PeYg915wks5EkUbO+w4IdmZVSiDBiXpQRB1yV2c2Vsde5O03XufDSz0=

# Whether to automatically accept the host key for your `repo` (in `wordpress_sites`) during git clone.
# To avoid man-in-the-middle attacks, set this to `false` and add repo host key to `known_hosts` above.
repo_accept_hostkey: true
