# Created by trellis-cli v1.5.1
# Documentation: https://docs.roots.io/trellis/master/wordpress-sites/

wordpress_sites:
  immex.nl:
    site_hosts:
    - canonical: immex.test
      redirects:
      - www.immex.test
    local_path: ../site
    admin_email: admin@immex.test
    multisite:
      enabled: false
    ssl:
      enabled: false
      provider: self-signed
    cache:
      enabled: false
